# Generated by Django 5.2.3 on 2025-07-19 11:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_insee', models.CharField(max_length=10)),
                ('elu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibelleContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default="Ecrire ici l'intitulé de l'opération", max_length=200)),
                ('description', models.TextField(default="Ecrire ici une description de l'opéraion")),
                ('date', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=10)),
                ('type_operation', models.CharField(choices=[('---', '---'), ('MNE', 'Maintenance du Numérique Éducatif'), ('AMO', 'Assistance à Maîtrise d’Ouvrage')], default='---', max_length=3)),
                ('service', models.CharField(choices=[('---', '---'), ('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='---', max_length=50)),
                ('est_liee', models.BooleanField(default=False)),
                ('collectivite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operation.collectivite')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operation.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('---', '---'), ('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='---', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SousOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(default='Écrire ici une description de la sous-opération')),
                ('date', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=10)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_operations', to='operation.entreprise')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.operation')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='technicien',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.technicien'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('sousoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.sousoperation')),
                ('libelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='operation.libellecontrat')),
            ],
            bases=('operation.sousoperation',),
        ),
        migrations.CreateModel(
            name='OperationLiee',
            fields=[
                ('sousoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.sousoperation')),
                ('operation_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_en_tant_que_sous_operation', to='operation.operation')),
            ],
            bases=('operation.sousoperation',),
        ),
    ]
