# Generated by Django 5.2.3 on 2025-06-25 17:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(default="Ecrire ici une description de l'opéraion"),
        ),
        migrations.AddField(
            model_name='operation',
            name='statut',
            field=models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=10),
        ),
        migrations.AddField(
            model_name='operation',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operation.technicien'),
        ),
        migrations.AddField(
            model_name='operation',
            name='titre',
            field=models.CharField(default="Ecrire ici l'intitulé de l'opération", max_length=200),
        ),
    ]
