# Generated by Django 5.2.3 on 2025-06-25 21:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_operation_date_operation_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_insee', models.CharField(max_length=10)),
                ('elu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SousOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(default='Écrire ici une description de la sous-opération')),
                ('date', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=10)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.operation')),
            ],
        ),
    ]
