# Generated by Django 5.2.3 on 2025-06-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_collectivite_entreprise_sousoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='collectivite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.collectivite'),
        ),
    ]
