# Generated by Django 5.2.3 on 2025-07-08 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_operation_collectivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='collectivite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='operation.collectivite'),
        ),
    ]
