# Generated by Django 5.2.3 on 2025-07-09 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_operation_collectivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operation.entreprise'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='collectivite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operation.collectivite'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='technicien',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.technicien'),
        ),
    ]
