# Generated by Django 5.2.3 on 2025-07-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_operation_entreprise_alter_operation_collectivite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousoperation',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_operations', to='operation.entreprise'),
        ),
    ]
