# Generated by Django 5.2.3 on 2025-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_sousoperation_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='service',
            field=models.CharField(choices=[('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='informatique', max_length=50),
        ),
        migrations.AddField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('MNE', 'Maintenance du Numérique Éducatif'), ('AMO', 'Assistance à Maîtrise d’Ouvrage')], default='MNE', max_length=3),
        ),
        migrations.AddField(
            model_name='technicien',
            name='service',
            field=models.CharField(choices=[('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='informatique', max_length=50),
        ),
    ]
