# Generated by Django 5.2.3 on 2025-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_operation_service_operation_type_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='service',
            field=models.CharField(choices=[('---', '---'), ('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='---', max_length=50),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('---', '---'), ('AMO', 'Assistance à Maîtrise d’Ouvrage'), ('MNE', 'Maintenance du Numérique Éducatif')], default='---', max_length=3),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='service',
            field=models.CharField(choices=[('---', '---'), ('assistance juridique', 'Assistance juridique'), ('bâtiment', 'Bâtiment'), ('conseil en énergie', 'Conseil en énergie'), ('informatique', 'Informatique'), ('voirie', 'Voirie')], default='---', max_length=50),
        ),
    ]
