# Generated by Django 5.2.3 on 2025-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_operation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('---', '---'), ('MNE', 'Maintenance du Numérique Éducatif'), ('AMO', 'Assistance à Maîtrise d’Ouvrage')], default='---', max_length=3),
        ),
    ]
