# Generated by Django 5.2.3 on 2025-07-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_alter_operation_type_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='est_liee',
            field=models.BooleanField(default=False),
        ),
    ]
