# Generated by Django 5.2.3 on 2025-07-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_operation_est_liee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousoperation',
            name='operation_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_en_tant_que_sous_operation', to='operation.operation'),
        ),
    ]
