# Generated by Django 5.2.3 on 2025-07-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_sousoperation_operation_liee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('sousoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.sousoperation')),
                ('libelle', models.CharField(choices=[('CT', 'CT'), ('DIAG_AMIANTE', 'Diag amiante'), ('DIAG_STRUCTURE', 'Diag structure'), ('MOE', 'MOE'), ('MTR', 'MTR'), ('SPS', 'SPS'), ('AUTRE', 'Autre')], max_length=100)),
                ('libelle_personnalise', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('operation.sousoperation',),
        ),
        migrations.RemoveField(
            model_name='sousoperation',
            name='operation_liee',
        ),
        migrations.CreateModel(
            name='OperationLiee',
            fields=[
                ('sousoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.sousoperation')),
                ('operation_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_en_tant_que_sous_operation', to='operation.operation')),
            ],
            bases=('operation.sousoperation',),
        ),
    ]
